spring:
  application:
    name: inventory-management-system

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3307/inventory_saas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: inventory_user
    password: inventory_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: InventoryHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:false}

  security:
    require-ssl: false

# Application-specific configuration
app:
  name: Inventory Management System
  version: 1.0.0

  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
      expiration: 28800 # 8 hours in seconds
      refresh-expiration: 604800 # 7 days in seconds

    password:
      expiry-days: 60
      history-count: 3
      min-length: 8
      max-length: 128
      require-uppercase: true
      require-lowercase: true
      require-digit: true
      require-special: true
      allowed-special-chars: "!@#$%^&*()_+-=[]{}|;:,.<>?"

    login:
      max-attempts: 5
      lockout-minutes: 30
      rate-limit-per-minute: 10

    session:
      timeout-minutes: 480 # 8 hours
      max-concurrent: 3
      cleanup-interval-seconds: 3600 # 1 hour

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Server configuration
server:
  port: 8082
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.inventory: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/inventory-management.log
    max-size: 10MB
    max-history: 30

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  show-actuator: true

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  mail:
    host: localhost
    port: 1025 # MailHog default port for testing
    # In development we use a local test SMTP (MailHog) which does not require
    # authentication. Override the global auth settings for the dev profile so
    # the mail health check doesn't fail when MAIL_USERNAME / MAIL_PASSWORD
    # are not set on developer machines.
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Disable the mail health indicator in dev so actuator doesn't fail when
  # a developer machine lacks SMTP credentials or the SMTP server doesn't
  # require authentication (e.g. MailHog). This keeps actuator useful during
  # local development. Restart the application for this to take effect.
  management:
    health:
      mail:
        enabled: false

logging:
  level:
    com.inventory: DEBUG
    org.springframework.security: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

  security:
    require-ssl: true

logging:
  level:
    com.inventory: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: /var/log/inventory-management/application.log

server:
  port: 8080
  ssl:
    enabled: false # Enable in production with proper certificates
